### ISSUE TITLE
AttributeError: 'StreamResponse' object has no attribute 'body' exception occurs when serving static html

### ISSUE THREAD

**Issue by rutsky** [aio-libs/aiohttp_debugtoolbar#12]
Steps to reproduce:

1. Setup official demo: https://github.com/aio-libs/aiohttp_debugtoolbar/blob/master/demo/README.rst
2. Create empty HTML file in static files directory:

   ```sh
   $ touch demo/static/test.html
   ```
3. Start demo:

   ```sh
   $ python demo/demo.py
   ```
4. Open `http://localhost:9000/static/test.html` in browser.

Expected behavior: empty html is being rendered in the browser and no errors occurs.
Observed behavior: empty html is being rendered in the browser, but in the console following stack trace occurs:

```sh
$ python demo/demo.py 
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:demo/demo.py:Server started at http://127.0.0.1:9000
ERROR:aiohttp.web:Error handling request
Traceback (most recent call last):
  File "/home/bob/stuff/aiohttp_debugtoolbar/demo/aiohttp_debugtoolbar/lib/python3.4/site-packages/aiohttp/server.py", line 272, in start
    yield from self.handle_request(message, payload)
  File "/home/bob/stuff/aiohttp_debugtoolbar/demo/aiohttp_debugtoolbar/lib/python3.4/site-packages/aiohttp/web.py", line 85, in handle_request
    resp = yield from handler(request)
  File "/home/bob/stuff/aiohttp_debugtoolbar/aiohttp_debugtoolbar/middlewares.py", line 141, in toolbar_middleware
    toolbar.inject(request, response)
  File "/home/bob/stuff/aiohttp_debugtoolbar/aiohttp_debugtoolbar/toolbar.py", line 57, in inject
    response_html = response.body
AttributeError: 'StreamResponse' object has no attribute 'body'
```

**Comment by asvetlov** [comment]
Thanks for so clean error report.
Toolbar should pass `StreamResponse` through gracefully.

**Comment by asvetlov** [comment]
Would you make a pull request?

**Comment by rutsky** [comment]
> Would you make a pull request?
I barely touched related code in my project and don't know this code at all, so I can't provide fix for it, sorry.

**Comment by asvetlov** [comment]
I'll fix it than

**Comment by rutsky** [comment]
Thanks, Andrew!
