### ISSUE TITLE
RoutesDebugPanel is broken with aiohttp >= 0.17

### ISSUE THREAD

**Issue by himikof** [aio-libs/aiohttp_debugtoolbar#13]
Method `RoutesDebugPanel.populate` tries to set `DebugPanel.data` property, which is marked as `aiohttp.helpers.reify`. Since aiohttp 0.17.0 (KeepSafe/aiohttp@51ea69d4c863b9a184293371b24e8d3e6651eb25), reified properties are readonly, so this assignment throws `AttributeError`.

**Comment by jettify** [comment]
Thanks for report!  Would you like to propose pull request?

**Comment by jettify** [comment]
New version has been released to pypi https://pypi.python.org/pypi/aiohttp_debugtoolbar/0.0.4
Thanks!
