### ISSUE TITLE
default settings host

### ISSUE THREAD

**Issue by stormandco** [aio-libs/aiohttp_debugtoolbar#20]
When i'm creating a server with 'localhost' on Mac OS like this:
```python
f = loop.create_server(handler, 'localhost', 8080)
```
then server returns IPv6 socket
```python
srv = loop.run_until_complete(f)
print('serving on', srv.sockets[0].getsockname()) # serving on ('::1', 8080, 0, 0)
```
and fails this check [here](https://github.com/aio-libs/aiohttp_debugtoolbar/blob/master/aiohttp_debugtoolbar/middlewares.py#L55):
```python
addr_in(last_proxy_addr, hosts)
```
So, debug-toolbar doesn't start
But when i set `127.0.0.1` or `0.0.0.0` everything runs ok. So my question: is this a bug or a feature? Should i add `::1` to `default_settings['hosts']` [here](https://github.com/aio-libs/aiohttp_debugtoolbar/blob/master/aiohttp_debugtoolbar/main.py#L36) or just use `127.0.0.1`?

**Comment by jettify** [comment]
Thanks for report! It is bug, could you make a PR?

**Comment by stormandco** [comment]
#22
Any tests required?
