### ISSUE TITLE
RoutesDebugPanel view source

### ISSUE THREAD

**Issue by stormandco** [aio-libs/aiohttp_debugtoolbar#23]
I found a bug with escaping `route_info['handler']` in `routes.jinja2` template

I fixed this and decided that it would be great to see the source code for handlers. I've extracted a source code using `inspect` module and customized it a little bit.

Eventually I've got something like this:
![routes](https://cloud.githubusercontent.com/assets/8763181/10105946/68b5ff32-63ba-11e5-9cf7-de2d924485fb.png)

So, I can make a PR if you find it useful.

**Comment by jettify** [comment]
Looks good! Please make RP! You have code highlighting in your screenshot, could you make sure that highlighting has same  style in exception view and as in routes view. Currenly code rendered in exception does not have highlighting at all.

**Comment by stormandco** [comment]
@jettify 
I wanted to make it in the same style as in exception view and maybe reuse some code. But seems like it has some classes to render each line. So, i decided to use `pre` and `code` tags with [highlight.js](https://github.com/isagalaev/highlight.js) library. Maybe I'll try to do the same with exception view?

And some other things to discuss:
Is it ok to use highlight.js? Or maybe some other library will be preferable? I chose `monokai` theme just for my favour. But I'm not sure that it fits in general design. So, I can switch to any other [theme](https://highlightjs.org/static/demo/)

**Comment by asvetlov** [comment]
highlight.js is perfect choice.
Yes, your theme doesn't fit to aiohttp_debugtoolbar css but we can tune it later.

**Comment by asvetlov** [comment]
Yes, exception view should be refactored to use highlightjs also.

**Comment by stormandco** [comment]
#26 
I will also try to replace traceback view

**Comment by jettify** [comment]
resolved via https://github.com/aio-libs/aiohttp_debugtoolbar/pull/26
