### ISSUE TITLE
Bootstrap glyphicons

### ISSUE THREAD

**Issue by stormandco** [aio-libs/aiohttp_debugtoolbar#27]
I played with traceback view and thought that it would be cooler to replace png-icons to bootstrap-glyphicons.
Here's how it looks with just spans:
![screen shot 2015-10-14 at 8 01 55 pm](https://cloud.githubusercontent.com/assets/8763181/10491555/dbfd6512-72af-11e5-9a4a-2bc4a48d02e9.png)

or with buttons and spans:
![screen shot 2015-10-14 at 8 01 16 pm](https://cloud.githubusercontent.com/assets/8763181/10491570/f070bcb0-72af-11e5-8331-063341ed7146.png)

What do you think?

**Comment by asvetlov** [comment]
I support the idea.
Would you create a Pull Request?

**Comment by jettify** [comment]
Good idea, I like second variant

**Comment by stormandco** [comment]
#29

**Comment by jettify** [comment]
fixed via https://github.com/aio-libs/aiohttp_debugtoolbar/pull/29
