### ISSUE TITLE
setup() should add the middleware

### ISSUE THREAD

**Issue by sloria** [aio-libs/aiohttp_debugtoolbar#33]
IMO, adding necessary middleware is the responsibility of a plugin's `setup()` function.

Current:
```python
import aiohttp_debugtoolbar
app = web.Application(middlewares=[aiohttp_debugtoolbar.middleware])
aiohttp_debugtoolbar.setup(app)
```

Proposed:

```python
import aiohttp_debugtoolbar
app = web.Application()
aiohttp_debugtoolbar.setup(app)
```

**Comment by jettify** [comment]
Agree. I did not do this first time because in early aiohttp versions it was not possible. Would you like to propose pull request?

**Comment by sloria** [comment]
Sure; I'll work on a PR within the next day or two.
