### ISSUE TITLE
Drop support for Python 3.3?

### ISSUE THREAD

**Issue by sloria** [aio-libs/aiohttp_debugtoolbar#36]
aiohttp>=0.18.0 no longer supports Python 3. Do you want to drop support for py33 in aiohttp_debugtoolbar as well?

**Comment by sloria** [comment]
Related question: do you still want to support aiohttp 0.14 as the minimum version? If so, I can send a PR which will test against aiohttp==0.14 as well as the latest version. If not, I can send a PR removing py33 from Travis and bumping up the min version of aiohttp in setup.py.

**Comment by sloria** [comment]
FWIW, the most recently-updated aiohttp libs (aiohttp_jinja2 and and aiohttp_cors) only support aiohttp>=0.18 . PR is in #37 . Let me know if any changes need to be made.

**Comment by jettify** [comment]
agree, aiohttp_debugtoolbar should follow aiohttp

**Comment by jettify** [comment]
resolved via #37
