### ISSUE TITLE
FIXME fouc

### ISSUE THREAD

**Issue by samuelcolvin** [aio-libs/aiohttp_debugtoolbar#46]
I'm getting an unpleasant flash of "#171;  FIXME: Debug Toolbar" from [here](https://github.com/aio-libs/aiohttp_debugtoolbar/blob/master/aiohttp_debugtoolbar/toolbar.py#L91-L92) every time I load a page.

I'm guess this relates to Pylons/pyramid_debugtoolbar#171?

Can we not just remove this content?

**Comment by samuelcolvin** [comment]
For our shared amusement, here's a gif of the problem:

![optimised](https://cloud.githubusercontent.com/assets/4039449/18791559/212ba7ba-81ab-11e6-8dd5-d181fde7d07d.gif)

**Comment by jettify** [comment]
Thats funny! I will try to fix that soon
