### ISSUE TITLE
Release 0.0.1

### ISSUE THREAD

**Issue by jettify** [aio-libs/aiohttp_debugtoolbar#6]
What do we need to make first alpha release? I've fixed demo app, where you can play with ported features and panels.

I guess some UI tweaking is required too, in order to to show difference from ``pyramid_debugtoolbar``. I am thinking about changing main color and placing ``aiohttp`` logo somewhere...

**Comment by asvetlov** [comment]
Demo app looks pretty cool.

Changing logo and color schema would be nice.
I think `pdtb.png` and `pyramid.png` should be replaced.
About color schema -- I prefer something based on aiohttp logo colors, as I've done for aiohttp sphinx schema.

I can help with UI redesigning if needed.

**Comment by asvetlov** [comment]
Pushed UI tweaks. 
Not perfect but better than nothing.

**Comment by jettify** [comment]
Released.
https://pypi.python.org/pypi/aiohttp_debugtoolbar/0.0.1
